-- Genre
INSERT INTO tb_genre (name) VALUES ('Aventura');
INSERT INTO tb_genre (name) VALUES ('Comédia');
INSERT INTO tb_genre (name) VALUES ('Ficção Científica');

-- Movie
-- Aventura
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Jumanji: Próxima Fase', 'O jogo bugou', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lzGTOie3M3Adb4eIAXqolDuxm3S.jpg', 'Tentado em revisitar o mundo de Jumanji, Spencer (Alex Wolff) decide consertar o jogo de videogame que permite que os jogadores sejam transportados ao local. Logo o quarteto formado por Smolder Bravestone (Dwayne Johnson), Moose Finbar (Kevin Hart), Shelly Oberon (Jack Black) e Ruby Roundhouse (Karen Gillan) ressurge, agora comandado por outras pessoas: os avôs de Spencer e Fridge (Danny DeVito e Danny Glover) assumem as personas de Bravestone e Finbar, enquanto o próprio Fridge (Ser Darius Blain) agora está sob a pele de Oberon.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Harry Potter e a Pedra Filosofal', 'Uma jornada além de sua imaginação', 2001, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7Hyl3IiKsaskhBnbkBU9jpAj57F.jpg', 'Harry Potter é um garoto órfão que vive infeliz com seus tios, os Dursleys. Ele recebe uma carta contendo um convite para ingressar em Hogwarts, uma famosa escola especializada em formar jovens bruxos. Inicialmente, Harry é impedido de ler a carta por seu tio, mas logo recebe a visita de Hagrid, o guarda-caça de Hogwarts, que chega para levá-lo até a escola. Harry adentra um mundo mágico que jamais imaginara, vivendo diversas aventuras com seus novos amigos, Rony Weasley e Hermione Granger.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Harry Potter e a Câmara Secreta', 'A Câmara Secreta foi aberta. Inimigos do herdeiro... cuidado!', 2002, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eeZBd4dFcaVx9KBijzIt8EIOv6r.jpg', 'Após as sofríveis férias na casa dos tios, Harry Potter se prepara para voltar a Hogwarts e começar seu segundo ano na escola de bruxos. Na véspera do início das aulas, a estranha criatura Dobby aparece em seu quarto e o avisa de que voltar é um erro e que algo muito ruim pode acontecer se Harry insistir em continuar os estudos de bruxaria. O garoto, no entanto, está disposto a correr o risco e se livrar do lar problemático.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Harry Potter e o Prisioneiro de Azkaban', 'Nada Será Como Antes / Segredos Serão Revelados', 2004, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/obKmfNexgL4ZP5cAmzdL4KbHHYX.jpg', 'O 3º ano de ensino na Escola de Magia e Bruxaria de Hogwarts se aproxima. Porém um grande perigo ronda a escola: o assassino Sirius Black fugiu da prisão de Azkaban, considerada até então como à prova de fugas. Para proteger a escola são enviados os Dementadores, estranhos seres que sugam a energia vital de quem se aproxima deles, que tanto podem defender a escola como piorar ainda mais a situação.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Harry Potter e o Cálice de Fogo', 'Tempos sombrios estão chegando', 2005, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/a5ARIgJrqDnxjyYRJaH7x9RrpKi.jpg', 'Em seu 4º ano na Escola de Magia e Bruxaria de Hogwarts, Harry Potter é misteriosamente selecionado para participar do Torneio Tribruxo, uma competição internacional em que precisará enfrentar alunos mais velhos e experientes de Hogwarts e também de outras escolas de magia. Além disso a aparição da marca negra de Voldemort ao término da Copa do Mundo de Quadribol põe a comunidade de bruxos em pânico, já que sinaliza que o temido bruxo está prestes a retornar.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Harry Potter e a Ordem da Fênix', 'O Mal Deve ser Confrontado', 2007, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7qKWTyYvkyIrWgkUOHiNxHv3FNK.jpg', 'Harry Potter está em seu quinto ano em Hogwarts e acaba ouvindo que muitos não sabem a verdade sobre seu encontro com Lord Voldemort. O Ministro de Mágica, Cornelius Fudge, indica Dolores Umbridge para ser a nova professora de Defesa Contra as Artes das Trevas, por acreditar que Dumbledore planeja tomar seu lugar. Porém, os métodos que ela usa são totalmente inapropriados. Harry, então, se reúne com um grupo de alunos para defender sua escola.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Harry Potter e o Enigma do Príncipe', 'Segredos escuros revelados', 2009, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/rwV9yFYUL6OJAw9Mh7PdnhHa0G3.jpg', 'No sexto ano de Harry em Hogwarts, Lord Voldemort e seus Comensais da Morte estão criando o terror nos mundos bruxo e trouxa. Dumbledore convence seu velho amigo Horácio Slughorn para retornar a Hogwarts como professor de poções após Harry encontrar um estranho livro escolar. Draco Malfoy se esforça para realizar uma ação destinada por Voldemort, enquanto Dumbledore e Harry secretamente trabalham juntos a fim de descobrir o método para destruir o Lorde das Trevas uma vez por todas.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Harry Potter e as Relíquias da Morte - Parte 1', 'Um caminho, um destino, um herói', 2010, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lntukFCBAd1CPSKfLocYWu1uIMx.jpg', 'Sem a orientação e proteção de seus professores, Harry, Rony e Hermione iniciam uma missão para destruir as horcruxes, que são as fontes da imortalidade de Voldemort. Embora devam confiar um no outro mais do que nunca, forças das trevas ameaçam separá-los. Os Comensais da Morte de Voldemort tomaram o controle do Ministério da Magia e de Hogwarts, e eles estão procurando por Harry enquanto ele e seus amigos se preparam para o confronto final.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Harry Potter e as Relíquias da Morte - Parte 2', 'Tudo termina aqui', 2011, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/icfcFCxyKTUqTmVYJbiBwLKnb1O.jpg', 'Harry Potter e seus amigos Rony Weasley e Hermione Granger seguem à procura das horcruxes. O objetivo do trio é encontrá-las e, em seguida, destruí-las, de forma a eliminar lorde Voldemort de uma vez por todas. Com a ajuda do duende Grampo, eles entram no banco Gringotes de forma a invadir o cofre de Bellatrix Lestrange. De lá retornam ao castelo de Hogwarts, onde precisam encontrar mais uma horcrux. Paralelamente, Voldemort prepara o ataque definitivo ao castelo.', 1);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Capitã Marvel', 'Mais alto. Mais longe. Mais rápido.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/nBS1vONGYrsL2C68C2oDQ3eKJR1.jpg', 'Capitã Marvel, parte do exército de elite dos Kree, uma raça alienígena, encontra-se no meio de uma batalha entre seu povo e os Skrulls. Ao tentar impedir uma invasão de larga escala na Terra, em 1995, ela tem memórias recorrentes de uma outra vida, como Carol Danvers, agente da Força Aérea norte-americana. Com a ajuda de Nick Fury, Capitã Marvel precisa descobrir os segredos de seu passado e pôr um fim ao conflito intergalático com os Skrulls.', 1);

-- Comédia
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Deadpool', 'Super Herói, super fodão e super Sexy.', 2016, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/38B4MIYNyWpehNBQ9pc22OQjsZ7.jpg', 'Baseado no anti-herói não convencional da Marvel Comics, Deadpool conta a história da origem do ex-agente das Forças Especiais que se tornou o mercenário Wade Wilson. Depois de ser submetido a um desonesto experimento que o deixa com poderes de cura acelerada, Wade adota o alter ego de Deadpool. Armado com suas novas habilidades e um senso de humor negro e distorcido, Deadpool persegue o homem que quase destruiu sua vida.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Deadpool 2', 'Ele não vem sozinho', 2018, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6WEbGTV5EaEJzFsZnTwslBgxcx4.jpg', 'Quando o super soldado Cable chega em uma missão para assassinar o jovem mutante Russel, o mercenário Deadpool precisa aprender o que é ser herói de verdade para salvá-lo. Para isso, ele recruta seu velho amigo Colossus e forma o novo grupo X-Force, sempre com o apoio do fiel escudeiro Dopinder.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Emma', 'Bonita, inteligente e rica', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/oz7RoRrNrqrT3KWG4ZSZ4f7D5aZ.jpg', 'Emma Woodhouse é uma jovem rica e inteligente, que não tem pretensões de se casar tão cedo, para ficar sempre perto do pai. Porém, isso não a impede de dar uma de casamenteira, tentando juntar casais que considere apropriados entre seus conhecidos, sem perceber os problemas causados com sua imaginação e teimosia.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Sócias em Guerra', 'The world of beauty is about to get ugly.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eefo9LSsBAUSetBhEVVD1nSgSHa.jpg', 'Mia e Mel (Tiffany Haddish e Rose Byrne), duas amigas inseparáveis, são felizes administrando a própria empresa de cosméticos até que uma malvada magnata da beleza (Salma Hayek) conspira para roubá-las. Esse maléfico plano separa as amigas, mas Mia e Mel descobrem que a única maneira de virarem o jogo e reaverem a empresa é trabalhando juntas. O ramo da beleza está prestes a ficar feio.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Magnatas do Crime', 'Criminal. Class.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg', 'Um traficante inglês muito poderoso tenta vender seu império extremamente lucrativo para um grupo de bilionários do Oklahoma.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Sociedade Secreta dos Segundos Filhos Reais', 'Nasceram para defender. Só precisam aprender como.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/oSSEcPDfwgZSv2i01Oqxdb9t8fI.jpg', 'Sam é uma adolescente rebelde da realeza, a segunda na linha de sucessão ao trono do reino da Ilíria. Assim como seu desinteresse pelo modo de vida real está no auge, ela descobre que tem habilidades sobre-humanas e é convidada a se juntar a uma sociedade secreta de membros da realeza extraordinários semelhantes, encarregados de manter o mundo seguro.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('MIB: Homens de Preto - Internacional', 'O mundo não vai se salvar sozinho.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/oatEgW9M00WC0OLB6JMOZA0MzE1.jpg', 'Por décadas a agência Homens de Preto protegeu a Terra da escória do universo, mas agora precisa lidar com a maior das ameaças: um traidor, justo quando a agência torna-se internacional. É neste contexto que Em tenta se tornar agente, já que teve uma experiência extraterrestre quando jovem e não teve sua memória apagada. Quem irá auxiliá-la nesta jornada é o atrapalhado agente H.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Shrek', 'O conto de fadas nunca contado.', 2001, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kZy4ApKnFhOekGmOlYtauF2xLWq.jpg', 'Em um pântano distante vive Shrek (Mike Myers), um ogro solitário que vê, sem mais nem menos, sua vida ser invadida por uma série de personagens de contos de fada, como três ratos cegos, um grande e malvado lobo e ainda três porcos que não têm um lugar onde morar. Todos eles foram expulsos de seus lares pelo maligno Lorde Farquaad (John Lithgow). Determinado a recuperar a tranquilidade de antes, Shrek resolve encontrar Farquaad e com ele faz um acordo: todos os personagens poderão retornar aos seus lares se ele e seu amigo Burro (Eddie Murphy) resgatarem uma bela princesa (Cameron Diaz), que é prisioneira de um dragão. Porém, quando Shrek e o Burro enfim conseguem resgatar a princesa logo eles descobrem que seus problemas estão apenas começando.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Shrek 2', 'Era uma outra vez...', 2004, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/zzuMpUoFcvICLxKPEKFOmRTJb7H.jpg', 'Após se casar com a Princesa Fiona (Cameron Diaz), Shrek (Mike Myers) vive feliz em seu pântano. Ao retornar de sua lua-de-mel Fiona recebe uma carta de seus pais, que não sabem que ela agora é um ogro, convidando-a para um jantar juntamente com seu grande amor, na intenção de conhecê-lo. A muito custo Fiona consegue convencer Shrek a ir visitá-los, tendo ainda a companhia do Burro (Eddie Murphy). Porém os problemas começam quando os pais de Fiona descobrem que ela não se casou com o Príncipe (Rupert Everett), a quem havia sido prometida, e enviam o Gato de Botas (Antonio Banderas) para separá-los.', 2);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Shrek Para Sempre: O Capítulo Final', 'Ele voltou mas é para o capítulo final.', 2010, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6SOTgqVw53ZoOpHEZ7T457c4Ixz.jpg', 'Shrek (Mike Myers) está entediado. Sua antiga vida de aventuras foi substituída pela de pacato pai de família. Casado com Fiona (Cameron Diaz) e pai de três filhos, Shrek sente falta da adrenalina e da liberdade que tinha no passado. Para recuperá-los, ele firma um pacto com Rumpelstiltiskin (Walt Dohrm). Imediatamente Shrek é levado a uma versão alternativa do Reino de Tão, Tão Distante, onde Fiona é uma temível ogro e ele não é mais reconhecido pelo Burro (Eddie Murphy) e o Gato de Botas (Antonio Bandera), seus melhores amigos.', 2);

-- Ficção Científica
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Skylines', 'To save our world she must invade theirs', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg', 'Quando um vírus ameaça transformar os híbridos alienígenas amigáveis que agora vivem na Terra contra os humanos, a capitã Rose Corley deve liderar uma equipe de mercenários de elite em uma missão ao mundo alienígena para salvar o que resta da humanidade.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Interestelar', 'O fim da terra não será o nosso fim.', 2014, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/xJHokMbljvjADYdit5fK5VQsXEG.jpg', 'As reservas naturais da Terra estão chegando ao fim e um grupo de astronautas recebe a missão de verificar possíveis planetas para receberem a população mundial, possibilitando a continuação da espécie. Cooper é chamado para liderar o grupo e aceita a missão sabendo que pode nunca mais ver os filhos. Ao lado de Brand, Jenkins e Doyle, ele seguirá em busca de um novo lar.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Tenet', 'O tempo acaba.', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/uTNLQuDxwX6C5EpHPGGLICXSbXC.jpg', 'Armado com apenas uma palavra – Tenet – e lutando pela sobrevivência do mundo inteiro, o Protagonista viaja através de um mundo crepuscular de espionagem internacional em uma missão que irá desenrolar em algo para além do tempo real.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Alita: Anjo de Combate', 'Um anjo cai. Uma guerreira se levanta.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/aQXTw3wIWuFMy0beXRiZ1xVKtcf.jpg', 'Abandonada em um ferro-velho de Iron City, a ciborgue Alita é encontrada pelo cientista Dyson Ido. Revitalizada, ela acorda sem memória e reconhecimento do mundo em que se encontra. Determinada a conhecer seu passado e explorar suas habilidades surpreendentes de luta, Alita se torna uma poderosa caçadora de recompensas, combatendo forças mortais.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('Bloodshot', 'A vingança de um herói está em seu sangue', 2020, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/5O2RwQuEar5n3VuDDF7OKWQAsOx.jpg', 'Bloodshot é um ex-soldado com poderes especiais: o de regeneração e a capacidade de se metamorfosear. Assassinado ao lado da esposa, ele é ressuscitado e aprimorado com nanotecnologia, desenvolvendo tais habilidades. Ao apagarem sua memória várias vezes, ele finalmente descobre quem realmente é e parte em um busca de vingança daqueles que mataram sua família.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Exterminador do Futuro: Destino Sombrio', 'Bem-vindo ao dia após o dia do julgamento.', 2019, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/9o9X8Ubr7t5WA09zvHO2uwwcCAW.jpg', 'A guerreira Sarah Connor se une a Grace, um híbrido entre ciborgue e humano, e ao T-800 para proteger a jovem Dani Ramos de um novo tipo de exterminador que chega do futuro à Cidade do México.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Exterminador do Futuro: Gênesis', 'Nova missão. Novo destino.', 2015, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/abHdPiLMO2ObgALEbI7Dr8u63sb.jpg', 'John Connor, líder da resistência humana contra Skynet, envia Kyle Reese de volta a 1984 para proteger sua mãe, Sarah. Porém, Reese se surpreende ao encontrá-la com um exterminador que age como seu protetor, e descobre que o passado foi alterado.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Exterminador do Futuro: A Salvação', 'O fim começa.', 2009, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/voInx2xld9xchDHp1QETjHVmANu.jpg', 'John Connor é designado para liderar a resistência humana ao domínio das máquinas, coordenadas pela Skynet e seu exército de exterminadores. Quando surge um estranho chamado Marcus Wright, cuja última memória que possui é de estar no corredor da morte, Connor precisa descobrir se ele foi enviado do futuro ou resgatado do passado, ao mesmo tempo em que a Skynet prepara seu ataque definitivo que pode aniquilar a humanidade.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Exterminador do Futuro 3 - A Rebelião das Máquinas', 'O dia do julgamento se aproxima.', 2003, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/3X43GIuFnadD2dFkT3TQePrag7y.jpg', 'Na intenção de concluir a missão ainda inacabada, a bela e perigosa máquina mortífera T-X é enviada para matar John Connor, líder da resistência humana contra as máquinas da Skynet. Para protegê-lo mais uma vez o ciborgue T-800 volta à cena.', 3);
INSERT INTO tb_movie (title, sub_title, year, img_url, synopsis, genre_id) VALUES ('O Exterminador do Futuro 2: O Dia do Julgamento', 'Hasta la Vista, Baby!', 1991, 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/aaaZMN7HsFEZPF5SqbdUls2K8yI.jpg', 'O jovem John Connor é a chave para a vitória da civilização sobre uma rebelião de robôs do futuro. No entanto, ele torna-se alvo de T-1000, um exterminador que pode assumir a forma que desejar e que foi enviado do futuro para matá-lo. Outro exterminador, o renovado T-800, também é enviado de volta ao passado para proteger o menino. Quando John e sua mãe embarcam na fuga com T-800, o menino cria um vínculo forte e inesperado com o robô.', 3);

-- Role
INSERT INTO tb_role (authority) VALUES ('ROLE_VISITOR');
INSERT INTO tb_role (authority) VALUES ('ROLE_MEMBER');

-- User
INSERT INTO tb_user (name, email, password) VALUES ('Bob Brown', 'bob@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Ana Silva', 'ana@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Maria Ferreira', 'maria@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');
INSERT INTO tb_user (name, email, password) VALUES ('Alex Henrique', 'alex@gmail.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG');

-- Association table between user and role
INSERT INTO tb_user_role (user_id, role_id) VALUES (1, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (2, 2);
INSERT INTO tb_user_role (user_id, role_id) VALUES (3, 1);
INSERT INTO tb_user_role (user_id, role_id) VALUES (4, 2);


-- Review
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Este é um filme muito interessante!', 2, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Inclusive foi o filme que me fez gostar da saga Harry Potter', 2, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Não gostei muito deste filme, mas gosto dos outros filmes da série', 2, 4);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Deadpool é filme bem engraçado haha', 11, 2);
INSERT INTO tb_review (text, movie_id, user_id) VALUES ('Interestelar é filme bem interessante que nos faz pensar sobre o espaço sideral', 22, 4);
